<?php

  /**
   * @file Core functionality for the faceted browsing of Solr-indexed Fedora Commons Objects
   * @author griffinj@lafayette.edu
   *
   */

require_once __DIR__ . '/includes/islandora_solr_facet_pages.inc';
require_once __DIR__ . '/includes/blocks.inc';
require_once __DIR__ . '/theme/theme.inc';

function islandora_dss_solr_facet_pages_block_view(&$data, $block) {

  switch($block->delta) {
    
  case 'islandora-solr-facet-pages':
    
    dpm($block);
    dpm($data);
    break;

  default:
    break;
  }
  }

/**
 * Implements hook_block_view_MODULE_DELTA_alter()
 *
 */
function islandora_dss_solr_facet_pages_block_view_islandora_solr_facet_pages_islandora_solr_facet_pages_alter(&$data, $block) {

  dpm($data);
  dpm($block);
}

/**
 * Implements hook_theme_registry_alter()
 *
 */
function islandora_dss_solr_facet_pages_theme_registry_alter(&$theme_registry) {

  $theme_registry['islandora_solr_facet_pages_letterer']['path'] = drupal_get_path('module', 'islandora_dss_solr_facet_pages') . '/includes';
  $theme_registry['islandora_solr_facet_pages_letterer']['file'] = 'islandora_solr_facet_pages.inc';

  $theme_registry['islandora_solr_facet_pages_results']['path'] = drupal_get_path('module', 'islandora_dss_solr_facet_pages') . '/theme';
}